version: '3.5'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    env_file:
      - .env # Use the .env file for environment variables
    networks:
      - ride-sharing-app-network # Connect to the custom network

  db:
    container_name: db
    build:
      context: .
      dockerfile: Dockerfile-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d # Mount the initdb directory
    ports:
      - 5434:5432
    networks:
      - ride-sharing-app-network # Connect to the custom network
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - db
    networks:
      - ride-sharing-app-network # Connect to the custom network
networks:
  ride-sharing-app-network:
    driver: bridge
